config/routes.rb
KillerFalt::Application.routes.draw do
  devise_for :admins
  devise_for :users

	resources :users do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
	end

  get '/edit_info', to: 'users#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_users', to: 'users#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_validation :create_login_and_password
  devise :database_authenticatable,
         #:registerable,
         #:recoverable,
         :rememberable,
         :trackable,:validatable
  has_many :killers_cards, class_name: "Card", foreign_key: :owner_id, dependent: :destroy
  has_one :victims_card, class_name: "Card", foreign_key: :victim_id, dependent: :destroy


  has_many :victims, through: :killers_cards
  has_one :killer, through: :victims_card

  has_many :source_events, class_name: 'Event', foreign_key: 'source_id'
  has_many :target_events, class_name: 'Event', foreign_key: 'target_id'
  has_many :new_target_events, class_name: 'Event', foreign_key: 'new_target_id'

  has_attached_file :avatar, styles: {medium: ['450x300', :jpg], thumb: ['150x100#', :jpg]},
                    url: "/system/avatars/:hash.:extension", hash_secret: 'killerfiztehbymorodeer',
                    default_url: "/system/avatars/:style/missing.jpg"

  def target
		victims.where(dead: nil).first
  end

  def die
		self.update_attribute(:dead,true)
  end

	def kill(user,password,method)
		if user.killing_word == password && self.target.id == user.id
			user.die
			user.victims_card.kill
			user.killers_cards.each do |card|
				Event.create(event_type:'card_transfer',source:self,target:user,card:card,method:method)
			end
			killers_cards << user.killers_cards
			Event.create(event_type:'murder',source:self,target:user,method:method, new_target: self.target, card_count: self.killers_cards.count)

		end
	end

	def full_name
		"#{name} #{surname}"
	end

  def email_required?
		false
  end

  def email_changed?
		false
  end

  def update_killing_word
	  self.killing_word = SecureRandom.base64(6)
	  self.save
  end

  def update_login_and_password
	  self.login = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
	  self.password = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
	  self.password_confirmation = self.password
	  self.temp_password = self.password
		self.save
  end

  def avatar_thumb
    avatar.url(:thumb)
  end

  def killers_cards_count
    killers_cards.count
  end

	private
		def create_login_and_password
      if self.login == ""

        self.login = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
        self.password = (0..8).map{ ('a'..'z').to_a[rand(26)]}.join
        self.password_confirmation = self.password
        self.temp_password = self.password
  			self.killing_word = SecureRandom.base64(6)
      end

      #self.save
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_filter :authenticate_admin!, only: [:new, :create, :destroy, :show, :index, :admin_kill, :edit,
  # :print_list, :set_target]
	#before_filter :authenticate_user!, only: [:edit_info]
  before_filter :stop_game, except: [:show, :index]

	def new
		@user = User.new
		@users = User.all
	end

	def create
		@user = User.create(params.require(:user).permit(:name,:surname,:avatar))
		if @user.save
			redirect_to new_user_path
		else
			render 'new'
		end
	end

	def destroy
		@user = User.find_by_id(params[:id])
		@user.destroy
		redirect_to users_path
	end

	def index
		#@users = User.paginate(page:params[:page])
		@users = User.all
	end

	def edit_info
		@user = current_user
	end

	def edit
		@user = User.find_by_id(params[:id])
	end

	def update

		if admin_signed_in?
			@user = User.find_by_id(params[:user][:id])
			if @user.update_attributes(params.require(:user).permit(:name,:surname,:login,:password,:password_confirmation,
        :avatar))
				redirect_to edit_user_path(@user), success: 'Параметры обновлены'
			else
				render 'edit'
			end
		elsif user_signed_in? and current_user.id.to_i == params[:user][:id].to_i
			@user = User.find_by_id(params[:user][:id])
			if @user.update_attributes(params.require(:user).permit(:login,:password,:password_confirmation))
				redirect_to new_user_session_path, success: 'Параметры обновлены'
			else
				render 'edit_info'
			end
		else
			redirect_to root_path, alert: 'У вас на это нет прав'
		end


	end

	def kill
		@target = User.find_by_id(params[:target][:id])
		@user = current_user
		if @user.target.id == @target.id
			puts 'starting killing'
			if @user.kill(@target,params[:target][:killing_word],'web')
				redirect_to root_path, success: 'Трупов всё больше, спасибо вам! )'
			else
				redirect_to root_path, alert: 'Промахнулись с жертвой или паролем. Брутфорс запрещен'
			end
		else
			redirect_to root_path, alert: 'У вас нет на это прав'
		end
	end

	def admin_kill
		@target = User.find_by_id(params[:target][:id])
		@user = User.find_by_id(params[:user][:id])
		if @user.target.id == @target.id
			puts 'starting killing'
			if @user.kill(@target,params[:target][:killing_word],'admin')
				redirect_to user_path(@user), success: 'Ок, убили.'
			else
				redirect_to user_path(@user), alert: 'С паролем не промахивайтесь =)'
			end
		end
	end

	def show
		@user = User.find_by_id(params[:id])
		@target = @user.target
		@events = Event.where(event_type:'murder',source_id:@user.id)
		@killers_card = Card.where(owner: @user, victim: @target)
	end

	def print_list
		@users = User.all
		respond_to do |format|
			format.html
			format.pdf do
				pdf = UsersPdf.new(@users)
				send_data pdf.render, filename: "userspdf.pdf",type:"application/pdf", disposition: "inline"
			end
		end
	end

	def set_target
		@user = User.find_by_id(params[:id])
		@target = User.find_by_id(params[:user][:id])
			Card.create(victim: @target, owner: @user)
		redirect_to @user
  end

  def revive
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(dead:nil)
      redirect_to @user
    else
      render 'show'
    end
  end

	private
		def is_current_user
			authenticate_user!
			unless params[:id].to_i == current_user.id.to_i
				redirect_to root_path, error: 'У вас на это нет прав'
			end
		end

    def stop_game
      redirect_to root_path
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.haml
=render 'shared/flash'
#body
	.row
		.large-12
			%h2 Редактирование входных данных
			=form_for(@user, {multipart: true}) do |f|
				=render 'shared/error_messages', object: f.object

				.row
					.large-8.columns
						=f.label :name
						=f.text_field :name

						=f.label :surname
						=f.text_field :surname

						=f.label :login
						=f.text_field :login

						=f.label :password
						=f.password_field :password

						=f.label :password_confirmation
						=f.password_field :password_confirmation

						-if admin_signed_in?
							=f.label :avatar
							=f.file_field :avatar
					.large-4.columns
						= image_tag @user.avatar.url(:medium)

				=f.hidden_field :id


				=f.submit 'Ок', class: 'button'

app/views/users/edit_info.haml
=render 'shared/flash'
#body
	.row
		%h2 Редактирование входных данных
		=form_for @user do |f|
			=f.label :login
			=f.text_field :login

			=f.label :password
			=f.password_field :password

			=f.label :password_confirmation
			=f.password_field :password_confirmation

			=f.hidden_field :id


			=f.submit 'Ок'

app/views/users/index.haml
.row
	%h1 Список игроков
	=link_to 'Список для печати', print_users_path

.row
	%p
		Живы
		= User.where(dead:nil).count
		, Мертвы
		= User.where(dead:'true').count


.row#body(ng-controller='UsersIndexCtrl')
	-#=foundation_paginate @users
	-#-iter = @users.offset
	%input(type="text" ng-model="query" placeholder="фильтр пользователей")
	%table
		%thead
			%td ID
			%td Аватарка
			%td Имя Фамилия
			%td Жив?
			%td Цель
			%td Всего карточек
			%td Редактировать
		/
			-@users.each do |user|
				%tr
					-#-#%td= iter=iter+1
					-#%td= user.id
					-#%td= link_to user.full_name, user_path(user)
					-#-if !user.dead
					-#	%td Да
					-#	%td
					-#		- if user.target.present?
					-#			= link_to user.target.full_name, user_path(user.target)
					-#		- else
					-#			———
					-#	%td= user.killers_cards.count
					-#
					-#-else
					-#	%td Нет
					-#	%td
					-#	%td
					-#%td= link_to 'Edit user', edit_user_path(user), class: 'tiny button'
					-#%td= link_to 'Delete user',  user_path(user), class: 'tiny button',method: :delete, confirm: 'Are you sure you wanna delete him?'
		%tr(ng-repeat='user in users | orderBy:"id" | filter: query')
			-#%td= iter=iter+1
			%td {{user.id}}
			%td
				%img(ng-src='{{user.avatar_thumb}}')
			%td
				%a(ng-href='/users/{{user.id}}') {{user.full_name}}

			%td(ng-show='user.dead') Убит
			%td(ng-hide='user.dead') Жив
			%td(ng-show='user.target')
				%a(ng-href='/users/{{user.target.id}}') {{user.target.full_name}}
			%td(ng-hide='user.target') —
			%td {{user.killers_cards_count}}
			%td
				%a(ng-href='/users/{{user.id}}/edit' class='tiny button') Edit user
			-#%td
			-#	%a{nghref:'/users/{{user.id}}/edit',class:'tiny button', dataMethod:'delete'} Delete user

=javascript_include_tag('https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js')
:javascript
	var app = angular.module('miptkiller',[])

	app.controller('UsersIndexCtrl',function($scope){
		$scope.users = #{@users.to_json(only:[:id,:dead],methods:[:full_name,:avatar_thumb,:killers_cards_count],
				include:{target: {only: [:id],methods:[:full_name]}})}
	})

app/views/users/new.haml
.row
	%h1 Добавляем игрока

	=form_for @user do |f|
		=f.label :name, 'Имя'
		=f.text_field :name, autofocus: true

		=f.label :surname, 'Фамилия'
		=f.text_field :surname

		=f.submit 'Зарегистрировать', class:'button'

	%ul
	-@users.each do |user|
		%li
			= user.full_name
			= user.login
			= user.temp_password

app/views/users/print_list.haml
.row
	%table
		-@users.each do |user|
			%tr
				%td="#{user.full_name}"
				%td="login:#{user.login}"
				- if user.passwordchanged?
					%td '*changed*'
				- else
					%td="pass:#{user.temp_password}"
				%td="killing_word:#{user.killing_word}"
				%td="target:#{user.target.present? ? user.target.full_name : '———'}"

app/views/users/show.haml
=render 'shared/flash'
#body
	.row
		.large-12.columns
			.row
				.large-8.columns
					%h2
						=@user.full_name
						- if admin_signed_in?
							(
							=link_to "Редактировать профиль", edit_user_path(@user)
							)


					%h4
						-if admin_signed_in?
							=link_to 'Удалить пользователя', user_path(@user), method: :delete, class: 'button',
							data: {confirm: 'Are you sure?'}
				.large-4.columns
					= image_tag @user.avatar.url(:medium)


			.panel
				- if @user.dead
					.alert-box.alert
						Пользователь мертв
						-if admin_signed_in?
							=link_to('Оживить', revive_user_path(@user),
							 data: {confirm: 'Вы точно хотите оживить игрока? '})
				- else
					- if @target.present?
						.row
							.large-2.columns
								=link_to @target.avatar.url(:original), class:'object_block',
								data: {colorbox: true,
								colorbox_height: '95%', colorbox_width: '95%'} do
									=image_tag @target.avatar.url(:thumb)
							.large-10.columns
								%h4
									Цель -
									= @target.full_name
									- if admin_signed_in?
										= link_to "...", user_path(@target)
										(
										=link_to 'Убрать цель', card_path(@target.victims_card), method: :delete, confirm: 'You sure?'
										)
								.row.collapse
									-if admin_signed_in?
										=form_tag admin_kill_user_path(@target) do
											.small-7.columns
												=text_field_tag 'target[killing_word]', nil, class: 'killing_word', |
													placeholder: @target.killing_word |
												=hidden_field_tag 'target[id]', @target.id
												=hidden_field_tag 'method', 'admin'
												=hidden_field_tag 'user[id]', @user.id
											.small-5.columns
												=submit_tag "Убить", class: 'button prefix'
									-else
										=form_tag kill_user_path(@target) do
											.small-7.columns
												=text_field_tag 'target[killing_word]', nil, class: 'killing_word', |
													placeholder: 'Killing word' |
												=hidden_field_tag 'target[id]', @target.id
												=hidden_field_tag 'method', 'web'
												=hidden_field_tag 'user[id]', @user.id
											.small-5.columns
												=submit_tag "Убить", class: 'button prefix'


					- elsif admin_signed_in?
						%h4 Выбрать цель
						=form_for User.new, url: {action: 'set_target'} do |f|
							=f.label :id
							-killable_users = User.includes(:victims_card).where(cards: {victim_id:nil}, dead: nil) |
								.where.not(id:@user.id) |

							=f.select :id, options_from_collection_for_select(killable_users, :id, :full_name)
							=f.submit 'Выбрать цель', class: 'button'





			%p.killing_word
				Пароль для убийства -
				= @user.killing_word

			-unless @user.dead
				%h2 Карточки
				%ul
				-@user.killers_cards.each do |card|
					%li= card.victim.full_name

			%h2 События
			%ul
			-@events.each do |event|
				%li
					= "#{event.source.full_name}"
					=" kills #{event.target.full_name}."
					="Now he has #{event.card_count} cards "
					-if event.new_target.present?
						="and new target - #{event.new_target.full_name}"