config/routes.rb
KillerFalt::Application.routes.draw do
  devise_for :admins
  devise_for :users

	resources :users do
		member do
			post 'kill'
			post 'admin_kill'
			post 'set_target'
      post 'revive'
		end
	end

  get '/edit_info', to: 'users#edit_info'
  get '/edit_admin_info', to: 'admins#edit_info'
  get '/print_users', to: 'users#print_list'
	resources :admins
  resources :events
  resources :cards

  root to: 'static_pages#home'
  get '/static_pages/home', to: 'static_pages#home'
	get '/rules', to: 'static_pages#rules'

  

end

app/views/shared/_error_messages.haml
- if object.errors.any?
	#error_explanation
		.alert-box.alert
			The form contains
			=pluralize(object.errors.count, "error")
			%ul
				-object.errors.full_messages.each do |msg|
					%li
						*
						=msg

app/views/shared/_flash.haml
.row
	- flash.each do |key, value|
		= content_tag(:div, value, :class => "alert-box flash #{key}")

app/views/shared/_footer.haml
%footer
	Создание и поддержка сайта - Юрий Дынников, ФАЛТ

app/views/shared/_ga.haml
:javascript

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-44191088-3']);
	_gaq.push(['_setDomainName', 'miptkiller.morodeer.ru']);
	_gaq.push(['_setAllowLinker', true]);
	_gaq.push(['_trackPageview']);

	(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript';
	  ga.async = true;

	ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
	var s = document.getElementsByTagName('script')[0];
	  s.parentNode.insertBefore(ga, s);
	})();

app/views/shared/_header.haml
%header
	.contain-to-grid
		%nav.top-bar
			.left_side
				#logo
					= link_to 'Киллер@Физтех', root_path

			.right_side
				- if admin_signed_in?
					=link_to 'Игроки', users_path
					=link_to 'События', events_path
					=link_to 'Добавить игроков', new_user_path
					-#=link_to 'Аккаунт', edit_admin_info_path
					=link_to 'Выйти из админки', destroy_admin_session_path, method: :delete

				-else
					- if !user_signed_in?
						=link_to 'Войти', new_user_session_path
					- else
						=link_to 'Аккаунт', edit_info_path
						=link_to 'Выйти', destroy_user_session_path, method: :delete